# Example of a service that uses Traefik as a reverse proxy

version: "3.8"
services:
  nginx:
    image: nginx:latest
    # ports:
    # - "80:80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vo.rule=Host(`example.com`)"
      - "traefik.http.services.vo.loadbalancer.server.port=80" # The port your service listens on
      - "traefik.http.routers.vo.entrypoints=websecure" # Use the entrypoint defined in Traefik's compose
      - "traefik.http.routers.vo.tls=true"

networks:
  default:
    external:
      name: web
