# Example of a service that uses Traefik as a reverse proxy

version: "3.8"
services:
  nginx:
    image: nginx:latest
    # ports:
    # - "80:80"
    restart: always
    labels:
      - "traefik.enable=true"
      #      - "traefik.http.routers.myservice.rule=Host(`example.com`)"
      - "traefik.http.routers.myservice.rule=Host(`example.com`)||Host(`www.example.com`)"
      - "traefik.http.services.myservice.loadbalancer.server.port=80" # The port your service listens on
      - "traefik.http.routers.myservice.entrypoints=websecure" # Use the entrypoint defined in Traefik's compose
      - "traefik.http.routers.myservice.tls=true"
      - "traefik.http.routers.myservice.middlewares=redirect-to-https" # Redirect HTTP to HTTPS
      - "traefik.http.routers.myservice.middlewares=redirect-www-to-non-www@file" # Redirect www to non-www

networks:
  default:
    external:
      name: web
