log:
  level: ERROR

api:
  insecure: false # Disable insecure API
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf/dynamic_conf.yml

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
